### ISSUE TITLE
Doesn't run on FF 56.0 - should run on earlier versions too?

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107-dev#1]
@lonalore I had to modify the manifest.json to install it on FF 56.0. (see below)

Ideally, people should be able to install it prior to upgrading to 57.0, unless there's some Quantum-specific code in there now? 

  ``` 
"applications": {
    "gecko": {
      "id": "e107-dev@e107.org",
      "strict_min_version": "56.0"
    }
  }
```

**Comment by lonalore** [comment]
If I know right the first Firefox released with WebExtesions API, is the v57. Does v56 also support WebExtesions?

**Comment by CaMer0n** [comment]
@lonalore Since FF 48 it seems. 

https://blog.mozilla.org/addons/2016/08/25/webextensions-in-firefox-50/

> WebExtensions is compatible with multiprocess Firefox, which began rolling out in Firefox 48 to people without add-ons installed.

https://blog.mozilla.org/addons/2016/06/09/webextensions-for-firefox-49/

> Since the release of Firefox 48, we feel WebExtensions are in a stable state. We recommend developers start to use the WebExtensions API for their add-on development.

**Comment by lonalore** [comment]
Thank you!
