### ISSUE TITLE
Vertical scroll-bar appears on main debug dropdown. 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107-dev#2]
Perhaps extend the height of the panel, or even better, reduce the font-size?

![image](https://user-images.githubusercontent.com/2825679/33510089-d9e6a8ba-d6bc-11e7-890e-eb2eb151d85a.png)

Is the font-size different inside each tab?
If so, maybe we can use this same font-size below (bold text) inside every tab?

![image](https://user-images.githubusercontent.com/2825679/33510145-63a824a2-d6bd-11e7-82a3-948f982e3e3b.png)

Also, the main 'debug mode' tab is the only tab without a box/table layout. 
Maybe the debug-mode list should look more like this? (space permitting) 
That would also give it the mouse-over hover style. What do you think?

![image](https://user-images.githubusercontent.com/2825679/33510171-c304cdd8-d6bd-11e7-8657-24d3af05ea80.png)

**Comment by lonalore** [comment]
Now the same font is used on the tabs. And I modified the first tab in order to use the same 'list-group' layout style.

**Comment by lonalore** [comment]
[e107-dev.zip](https://github.com/e107inc/e107-dev/files/1524917/e107-dev.zip)
