### ISSUE TITLE
FF Manifest ID needs to be changed, in order to replace old e107 debugger

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107-dev#3]
From Mozilla: 

Your add-on failed validation with 1 error.

> The add-on ID in your manifest.json or install.rdf (e107-dev@e107.org) does not match the ID of your add-on on AMO ({ce54f00e-29ba-444c-ab72-f845d4c57612}

**Comment by lonalore** [comment]
Can you provide me an access to AMO? I would like to see the publishing process. How was this ID generated? Did you try to publish e107-dev as a completely new add-on, or did you try to upload it to the existing e107 debugger?

**Comment by CaMer0n** [comment]
@lonalore I uploaded it as an 'upgrade' so that existing users would be notified. I can give you access, but there really isn't much to see. I clicked "Upload update" and then uploaded the file, after that the notification was displayed.

**Comment by lonalore** [comment]
Please try with this:
[e107-dev.zip](https://github.com/e107inc/e107-dev/files/1530313/e107-dev.zip)

**Comment by lonalore** [comment]
If it's okay, I will create a release and upload it to Google.

**Comment by CaMer0n** [comment]
Submitted to Mozilla.. now we wait! :-)
Yes please upload to Google! Thanks 👍

**Comment by lonalore** [comment]
Submitted to Google, and ready to use:
https://chrome.google.com/webstore/detail/e107-dev/ikpmmbnjfndjmpmehlgeeinfkiaafdkf?hl=en

**Comment by CaMer0n** [comment]
@lonalore It was rejected. No reason given, but I believe the "version" is in conflict with the original. (v1.0)
Can we try again by changing the version on the FF one to 2.0 ?

**Comment by lonalore** [comment]
Could you please upload it as a new add-on? I've already uploaded it to Google with v1.0.0, and I don't think it's a good idea to develop the same extension files under different version numbers in the future. But if you really want to upload it as an update to the existing e107 debugger, then feel free to modify the manifest file before uploading it to Mozilla. Manifest file contains the version number.

**Comment by CaMer0n** [comment]
I changed the manifest. If they reject again, I'll upload as a separate plugin.

**Comment by CaMer0n** [comment]
https://addons.mozilla.org/en-US/firefox/addon/e107-dev/
Sorry,was unable to change the "by CaMer0n". 
At least we retained the reviews/history.

**Comment by lonalore** [comment]
No worries. :) Btw, the next version will be 2.x.x, so we will not need to use two different versions.
